[package]
name = 'item_nft'
version = '1.0.0'
authors = []

[addresses]
admin = "_"
item = '_'

[dev-addresses]
admin = "0xfa"
item = "0xfb"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

[dev-dependencies]
